image: maven:3.6.1

pipelines:
  custom:
    manual:
       - step:
           size: 2x
           caches:
             - gradle
             - gradlewrapper
             - maven
           script:
             - ./dspace-api/src/test/data/dspaceFolder/bin/install_grobid.sh
             - mvn clean install license:check -DskipUnitTests=false -Pdspace-rest -DskipITs=false -Pdspace-rest -DskipIntegrationTests=false -P !assembly -B -V -Dsurefire.rerunFailingTestsCount=2

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper